// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fddnbzyqduwpkbeszhow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkZG5ienlxZHV3cGtiZXN6aG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzg4OTIsImV4cCI6MjA2MTYxNDg5Mn0.rfD1Pu-0PStU106u-UK9sNb1OCSKTP_r8FfKHSGk4xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);